{% set version = "3.1.23" %}
{% set build = 1 %}

package:
    name: celery
    version: {{ version }}

source:
    fn: celery-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/c/celery/celery-{{ version }}.tar.gz
    md5: c6f10f956a49424d553ab1391ab39ab2

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - celery = celery.__main__:main
        - celeryd = celery.__main__:_compat_worker
        - celerybeat = celery.__main__:_compat_beat
        - celeryd-multi = celery.__main__:_compat_multi

requirements:
    build:
        - python
        - setuptools
        - pytz
        - billiard >=3.3.0.23,<3.4
        - kombu >=3.0.34,<4.0
    run:
        - python
        - pytz
        - billiard >=3.3.0.23,<3.4
        - kombu >=3.0.34,<4.0
        - sqlalchemy

test:
    imports:
        - celery
        - celery.app
        - celery.apps
        - celery.backends
        - celery.backends.database
        - celery.bin
        - celery.concurrency
        - celery.contrib
        - celery.events
        - celery.fixups
        - celery.loaders
        - celery.security
        - celery.task
        - celery.utils
        - celery.utils.dispatch
        - celery.worker

about:
    home: http://celeryproject.org
    license: BSD License
    summary: Distributed Task Queue

extra:
    recipe-maintainers:
        - kwilcox
