{% set name = "celery" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a650525303ee866fb0c62c82f68681fcc2183eebbfafae552c27d30125fe518b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - celery = celery.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytz
    - billiard >=3.6.1,<4.0
    - kombu >=4.6.7,<5.0
    - vine >=1.3.0
    - sqlalchemy
    - cryptography

test:
  requires:
    - case >=1.3.1
    - pytest >=3.0
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.apps
    - celery.backends
    - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.task
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - celery --version
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit      # [py3k]

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - kwilcox
    - pmlandwehr
    - sodre
    - edetec
    - mcs07
