travis:
  secure:
    BINSTAR_TOKEN: GkCzhucauQxi7nv+cTxHsSKAw2XCp15CU6KHhFq+oLjE/qh/ulbNXb/ucAYvoGy8dlt/ORM6LdJBCr48QV6B5BdAd0AyosgfdwRny0bP5CNZOwS0Wyuw/R+osK6BWmvsMuHsMiyGgtrLpVh37bVidcxdNTN/SrMMm0V/pTBcnscBo5f0ErexFm/oCRze5Qa55zehW183pM9vyUU3PS78wC3u6LR6sugVF8h59O9Dark0qthz/CIJMmXpN65k+SAwg0Fby7TAYt3BUzppNqQWOh75lQMTj/loKktzT/WdPDHVPRVJhYBy/ceH4gbGP2Z0vZS/GR2xeNz05sB2nI12vGZqtuqdHSttTi6KlU091Jo8fiVYDKXvBBJskym9rB6fChWm0s/CXlj/LrtXESaF8DcVSMti3FeKdVjg/haTym1U3IxhEVk3hZa8gc9XkhMsPLpfpgwlA0LImFSM7vzjTACQVm9WkbPN3EaAOGb0rvN/QK+hDFToL4A+QrEKR+BAHmoe22fCeh9VhYTuZs00QqNdKyrjVloUGcLWBAvaCRnWdSPPjj682cLq1BbD5HeNdNSoYY6TcY1XPKGadJ7HkgXCIuTZcawe9dUIlM3hHoj2PmXlmDuTTzR1Mnlgvdrz/jOfWSQoj/o/K2WylcGXtgcj8E1zmsYliDZ6IeKhpgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
