travis:
  secure:
    BINSTAR_TOKEN: hH4nLQbkDIgdrTcdaCLaBe5hPWq21kTo0nRax9XDLr2ccUGkIEJ7NF+8qyQc4YuK3JMkdF1wA6lzspRq675RtnkYGJZb9J8HRzulYgglNJZ/h7fUjSoS3raTOqtjFQ/Sec4ZjoUtjyu3Bf/20jrkhAXgM0D728g5wWGwtzZFEBO+WL05/mXBf3lhYX2R8y2PaQ+AF1h/ycfXLXTnz6AA+MH0ZIS6bRZoPXU+AO8NoiHE62FrRZJA37l9VWu95re0kJATOLxiPGIVfC+oCpt8pBQ3NjJFyTwgxT2lx4BW0EMCKO4rQqsWirmIujG3QRPtV2fwC5TLbWvzeO4PKW+GPirOqljlIKNEBWBXzkJyKVTQhjlLIgsr707l8O+3Ih2/iYFC+eyJAbQO6GSzpmc7rs9EM5Ob2bRzzg014zag0K+dRn+iZZYhoqAV2+SMOl6NMuRMwo8PwaLJPbI3g//SXv+/JcgOdVuiLpXrDcPQbcBlop1pw7TOqiV9gbNZaXMEXph0ZR+I4LrH3Xg0qpo6R6zQdzVXN1kzbt0F590mPK/Cqo8YwLKkn2s9t8PJKjCT6pnGSBT3BDhEnWIjkAQf+N0ydU5W0hCch3CK6ipxxPherPyuIVvNuz8FpnXcGfus9vnQ52/2VIfVaPfBCgvIplYuAmmYpqiel7i2KO8j54I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
